### ISSUE TITLE
US-4: Fogarbejdere kan lave en guide til den solgte carport

### ISSUE THREAD

**Issue by Magnewei** [Magnewei/EksamensOpgave_FogCarport#12]
### Userstory
Som Fog medarbejder, ønsker jeg at kunne lave en guide til den givne carport, en kunde har bestilt, samt en liste over materialer. 

---
### Acceptkriterier
Givet at kunden har sendt en formular om et tilbud, samt at vi har materialerne til at bygge carporten. Når kunden har betalt for tilbuddet, skal jeg kunne sende en guide til hvordan carporten skal bygges, under “ordrer”.

**Comment by Nazarenee** [comment]
stavefejli

**Comment by Magnewei** [comment]
Er faktisk ikke sikker på hvad der menes med guide. Afsend pdf fil?
